<?php
/**
 * Language labels for module "tools_txw4xbackupM1"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'title' => 'Backup',
		'f1s1_title' => 'Make Full Backup',
		'f1s1_title2' => 'Delete Previous Backups',
		'flsl_title3' => 'Restore Backup',
		'flsl_title4' => 'Module Settings',
		'flsl_title5' => 'About Full Backup',
		'f1s1_label_all' => 'All',
		'f1s1_backupcreated' => 'Created backup.',
		'clearWarning' => '<b><font color=red>Warning:</font></b><br>You are about to clear every *.gz file located at your typo3temp/ directory (even if it is not a previous backup!).',
		'function1' => 'Backup',
		'function2' => 'Restore',
		'function3' => 'Clear',
		'function4' => 'Settings',
		'function5' => 'About',
		'avBckps' => 'Available backups:',
		'submit_backupnow' => 'Backup now!',
		'wholetypo3conf' => 'Include the whole typo3conf directory',
		'restoreFile' => 'Restore file',
		'clearAll' => 'Clear All *.gz files!',
		'clearFile' => 'Clear file ',
		'clearedOk' => ' was deleted!',
		'restoreOk' => 'was restored!',
		'clearedAllOk' => 'All *.gz files were deleted!',
		'executed' => 'Executed',
		'backupCreated' => 'Backup Created!',
		'downloadFile' => 'Download file',
		'altDownloadMsg' => 'If download doesnt start automatically, you can download the file',
		'confMsg' => '(<em>Notice: You may need to clear the cache after configuration of the extension. This is required if the extension adds TypoScript depending on these settings.</em>)<br /><br />',
		'confMsg_2' => 'Sorry. This feature is disabled. Please, ask your system administrator to modify the extension settings.',
		'confMsg_3' => 'Configuration Needed:',
		'confMsg_4' => 'For this extension to work properly, you need to set the tar path for non-windows servers, or the 7-Zip path for windows servers.',
		'confMsg_5' => 'Configuration Saved!',
		'here' => 'download archive here',
		'restore' => 'Restore File',
		'noFile' => 'There is no Backup file!',
		'e_files' => 'Excluded Files',
		'e_files2' => 'Files in Exclude List',
		'e_files3' => ' were not processed',
		'errorLog1' => 'There was an operation report',
		'errorLog2' => 'It can be seen here',
		'errorLog3' => 'Operation log',
		'errorLog4' => 'sql could not be deleted',
		'time_elapsed' => 'Time elapsed (in seconds)',
		'mkbkp_message' => 'The BACKUP tool will check whether <b>%s</b>, which is the server\'s user name, has the appropriate permissions and ownerships to do the backup.&nbsp;If forced to proceed, the tar file will only include those files with <em>read permission</em> for <b>%s</b>.<br><br>The RESTORE tool <font color=red>will not allow</font> you to restore the tar file until <em>write permissions</em> are fixed, unless forced to.',
		'mkbkp_warning' => 'Do backup WITHOUT permissions check?',
		'mkbkp_warning1' => 'Proceed without permissions check.',
		'restoreForm1' =>'First Step:',
		'restoreForm2' =>'Verify file for problems',
		'restoreForm3' =>'File name for verification:',
		'restoreForm4' =>'File date and time:',
		'restoreForm5' =>'Yes',
		'restoreForm6' =>'Verify this file.',
		'restoreForm7' =>'Do restore WITHOUT permissions check?',
		'restoreForm8' =>'Proceed without permissions check.',
		'restoreForm9' =>'Submit',
		'restoreForm10' =>'The operation was not performed!',
		'restoreForm11' =>'Back',
		'restoreForm12' =>'Ok!',
		'restoreForm13' =>'Ommited! (Proceed without permissions check.)',
		'restoreForm14' =>'Second Step:',
		'restoreForm15' =>'Confirm RESTORE',
		'restoreForm16' =>'File name for restoration:',
		'restoreForm17' =>'I want to RESTORE my TYPO3 installation with this file.',
		'restoreForm18' =>'A security backup of the data available before RESTORE operation was generated:',
		'restoreForm19' =>'Please, select which file to restore:',
	),
	'dk' => Array (
	),
	'de' => Array (
		'title' => 'Backup',
		'f1s1_title' => 'Was mцchten Sie sichern?',
		'f1s1_label_all' => 'Alles',
		'f1s1_backupcreated' => 'Backup erstellt.',
		'submit_backupnow' => 'Backup jetzt erstellen!',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
		'title' => 'Kopia zapasowa',
		'f1s1_title' => 'Zapisz kopiк zapasow±',
		'f1s1_title2' => 'Usuс poprzednie kopie zapasowe',
		'flsl_title3' => 'Odtwуrz kopiк zapasow±',
		'f1s1_label_all' => 'Wszystkie',
		'f1s1_backupcreated' => 'Utworzono kopiк zapasow±',
		'clearWarning' => '<b><font color=red>UWAGA!</font></b><br>Zamierzasz usun±ж KAЇDY plik z rozszerzeniem *.gz z katalogu typo3temp/. Oznacza to rуwnieї pliki nie bкd±ce kopi± zapasow±!',
		'function1' => 'Utwуrz kopiк zapasow±',
		'function2' => 'Odtwуrz kopiк zapasow±',
		'function3' => 'Wyczy¶ж lokalne kopiк',
		'function4' => 'O...',
		'avBckps' => 'Dostкpne kopie zapasowe',
		'submit_backupnow' => 'Utwуrz kopiк zapasow±',
		'wholetypo3conf' => 'Doі±cz do kopii caіy katalog typo3conf/',
		'restoreFile' => 'Odtwуrz kopiк zapasow±',
		'clearAll' => 'Usuс WSZYSTKIE pliki *.gz!',
		'clearFile' => 'Usuс kopiк zapasow±',
		'clearedOk' => 'zostaі usuniкty!',
		'restoreOk' => 'zostaі odtworzony!',
		'clearedAllOk' => 'WSZYSTKIE pliki *.gz zostaіy usuniкte.',
		'executed' => 'Wykonano',
		'backupCreated' => 'Utworzono kopiк zapasow±',
		'downloadFile' => 'Pobierz plik',
		'altDownloadMsg' => 'Je¶li pobieranie nie rozpocznie siк automatycznie, moїesz pobraж plik',
		'here' => 'tutaj',
		'restore' => 'Odtwуrz kopiк',
		'noFile' => 'Nie ma kopii zapasowych.',
	),
	'si' => Array (
	),
	'fi' => Array (
		'title' => 'Varmistus',
		'f1s1_title' => 'Tee tдydellinen varmistus',
		'f1s1_title2' => 'Poista vanhat varmistukset',
		'flsl_title3' => 'Palauta varmistus',
		'flsl_title4' => 'Modulin asetukset',
		'flsl_title5' => 'Yleistд tдydestд varmistuksesta',
		'f1s1_label_all' => 'Kaikki',
		'f1s1_backupcreated' => 'Varmistus luotu',
		'clearWarning' => '<b><font color=red>Varoitus:</font></b><br>Olet aikeissa tyhjentдд kaikki *.gz tiedostot jotka sijaitsevat typo3temp/ hakemistossa (jopa ne, jotka eivдt ole aiempia varmistuksia!).',
		'function1' => 'Varmistus',
		'function2' => 'Palauta',
		'function3' => 'Tyhjдд',
		'function4' => 'Asiasta',
		'function5' => 'Yleistд',
		'avBckps' => 'Kдytettдvissд olevat varmistukset:',
		'submit_backupnow' => 'Varmista nyt!',
		'wholetypo3conf' => 'Ota mukaan koko typo3conf hakemisto',
		'restoreFile' => 'Palauta tiedosto',
		'clearAll' => 'Tyhjдд kaikki *.gz tiedostot!',
		'clearFile' => 'Tyhjдд tiedosto',
		'clearedOk' => 'poistettiin!',
		'restoreOk' => 'palautettiin !',
		'clearedAllOk' => 'Kaikki *.gz tiedostot poistettiin!',
		'executed' => 'Suoritettiin',
		'backupCreated' => 'Varmistus luotu!',
		'downloadFile' => 'Imuroi tiedosto',
		'altDownloadMsg' => 'Jos imurointi ei kдynnisty automaattisesti, imuroi tiedosto',
		'confMsg' => '(<em>Huomaa: Sinun on ehkд tyhjennettдvд vдlimuisti laajennusten muokkausten jдlkeen. Tдmд on tarpeen jos laajennus lisдд TypoScript:iin liittyviд osia asetuksiin.</em><br /><br />',
		'confMsg_2' => 'Valitan. Tдmд mahdollisuus on estetty. Ole ystдvдllinen ja pyydд jдrjestelmдn haltijaa muokkaamaan laajennuksen asetuksia.',
		'confMsg_3' => 'Konfigurointi tarvitaan:',
		'confMsg_4' => 'Jotta laajennus toimisi oikein, tarvitsee Sinun asettaa polku tar-ohjelmalle non-windows ympдristцssд tai polku 7-zip ohjelmalle windows palvelimissa.',
		'confMsg_5' => 'Konfigurointi talletettu!',
		'here' => 'tдstд.',
		'restore' => 'Palauta tiedosto',
		'noFile' => 'Backup (varmistus) tiedostoa ei lцydy !',
		'e_files' => 'Poissuljettavat tiedostot',
		'e_files2' => 'Tiedostot poissuljettavien listalla',
		'e_files3' => 'ei kдsitelty',
		'errorLog1' => 'Olemassa ole toimintaraportti',
		'errorLog2' => 'Jonka voi nдhdд tддltд',
		'errorLog3' => 'Toimintaloki',
		'errorLog4' => 'sql ei ei voitu poistaa',
	),
	'tr' => Array (
	),
	'se' => Array (
		'title' => 'Backup',
		'f1s1_title' => 'Gцr en fullstдndig backup',
		'f1s1_title2' => 'Ta bort tidigare backups',
		'flsl_title3' => 'Еterstдll backup',
		'f1s1_label_all' => 'Allt',
		'f1s1_backupcreated' => 'Skapad backup.',
		'clearWarning' => '<b><font color=red>Varning:</font></b><br>Du hеller pе att ta bort alla *.gz-filer som finns i din tyop3temp/ -katalog (дven om de inte дr tidigare backup-filer!).',
		'function1' => 'Backup',
		'function2' => 'Еterstдll',
		'function3' => 'Tцm',
		'function4' => 'Om',
		'avBckps' => 'Tillbudsstеende backup:ar',
		'submit_backupnow' => 'Backup nu!',
		'wholetypo3conf' => 'Inkludera hela typo3conf-katalogen',
		'restoreFile' => 'Еterstдll fil',
		'clearAll' => 'Tцm alla *.gz-filer',
		'clearFile' => 'Tцm fil',
		'clearedOk' => 'har tagits bort!',
		'restoreOk' => 'har еterstдllts!',
		'clearedAllOk' => 'Alla *.gz-filer har tagits bort!',
		'executed' => 'Utfцrd',
		'backupCreated' => 'Backup skapad!',
		'downloadFile' => 'Ladda ner fil',
		'altDownloadMsg' => 'Om nerladdningen inte startar automatiskt, kan du ladda ner filen',
		'here' => 'hдr',
		'restore' => 'Еterstдll fil',
		'noFile' => 'Det finns ingen backup-fil!',
	),
	'pt' => Array (
	),
	'ru' => Array (
		'title' => 'Резервное копирование',
		'f1s1_title' => 'Создать полную копию',
		'f1s1_title2' => 'Удалить предыдущие копии',
		'flsl_title3' => 'Восстановить из копии',
		'flsl_title4' => 'Настройки модуля',
		'flsl_title5' => 'О резервном копировании',
		'f1s1_label_all' => 'Всё',
		'f1s1_backupcreated' => 'Копия создана',
		'clearWarning' => '<b><font color="red">Внимание!</font></b><br />Вы собираетесь удалить все *.gz-файлы в Вашем каталоге typo3temp/ (даже если это не резервные копии!)',
		'function1' => 'Копировать',
		'function2' => 'Восстановить',
		'function3' => 'Очистить',
		'function4' => 'Настройки',
		'function5' => 'Что это?',
		'avBckps' => 'Доступные копии:',
		'submit_backupnow' => 'Создать копию!',
		'wholetypo3conf' => 'Включить весь каталог typo3conf',
		'restoreFile' => 'Восстановить файл',
		'clearAll' => 'Удалить все *.gz-файлы!',
		'clearFile' => 'Удалить файл',
		'clearedOk' => 'был удалён!',
		'restoreOk' => 'был восстановлен!',
		'clearedAllOk' => 'Все *.gz-файлы были удалены!',
		'executed' => 'Выполнено',
		'backupCreated' => 'Резервная копия создана!',
		'downloadFile' => 'Скачать файл',
		'altDownloadMsg' => 'Если скачивание не начнётся автоматически, Вы можете скачать файл',
		'confMsg' => '(<em>Обратите внимание: Вам может потребоваться очистить кэш после настройки этого расширения. Это требуется, если расширение добавляет свой TypoScript в зависимости от этих настроек.</em>)<br /><br />',
		'confMsg_2' => 'Извините. Эта возможность отключена. Пожалуйста, попросите Вашего системного администратора изменить настройки расширения.',
		'confMsg_3' => 'Требуемые настройки:',
		'confMsg_4' => 'Чтобы это расширение работало правильно, необходимо установить путь к программе TAR на не-Windows-системах и путь к 7-zip для Windows-серверов.',
		'confMsg_5' => 'Настройки сохранены!',
		'here' => 'загрузить архив тут',
		'restore' => 'Восстановить файл',
		'noFile' => 'Нет файлов с резервными копиями!',
		'e_files' => 'Исключённые файлы',
		'e_files2' => 'Файлы в списке исключений',
		'e_files3' => 'не были обработаны',
		'errorLog1' => 'Случилась ошибка',
		'errorLog2' => 'Её можно посмотреть тут',
		'errorLog3' => 'Лог операции',
		'errorLog4' => 'Невозможно удалить SQL',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
		'title' => 'Backup',
		'f1s1_title' => 'Teljes backup kйszнtйse',
		'f1s1_title2' => 'Elхzх backupok tцrlйse',
		'flsl_title3' => 'Backup visszaбllнtбsa',
		'flsl_title4' => 'Modul beбllнtбsok',
		'flsl_title5' => 'A teljes backuprуl',
		'f1s1_label_all' => 'Цsszes',
		'f1s1_backupcreated' => 'Backup lйtrehozva.',
		'clearWarning' => '<b><font color=red>Figyelem:</font></b><br>Le akarod tцrцlni az цsszes typo3temp/ kцnyvtбrban talбlhatу *.gz file-t (akkor is, ha az nem egy elхzх backup file).',
		'function1' => 'Backup',
		'function2' => 'Visszaбllнtбs',
		'function3' => 'Tцrlйs',
		'function4' => 'Beбllнtбsok',
		'function5' => 'Info',
		'avBckps' => 'Elйrhetх backupok:',
		'submit_backupnow' => 'Backup most!',
		'wholetypo3conf' => 'Az egйsz typo3conf kцnyvtбrat beleйrtve',
		'restoreFile' => 'File visszaбllнtбsa',
		'clearAll' => 'Az цsszes *.gz file tцrlйse!',
		'clearFile' => 'File tцrlйse',
		'clearedOk' => 'tцrцlve!',
		'restoreOk' => 'visszaбllнtva!',
		'clearedAllOk' => 'Az цsszes *.gz file tцrцlve!',
		'executed' => 'Lefuttatva',
		'backupCreated' => 'Backup lйtrehozva!',
		'downloadFile' => 'File letцltйse',
		'altDownloadMsg' => 'Ha a letцltйs nem indul el magбtуl, letцltheted a file-t',
		'confMsg' => '(<em>Figyelem: A bхvнtmйny beбllнtбsa utбn lehet, hogy tцrцlni kell a cache-t. Ez akkor szьksйges, ha a bхvнtmйny TypoScript-et vбltoztat a beбllнtбsoktуl fьggхen.</em>)<br /><br />',
		'confMsg_2' => 'Sajnбlom, ez a lehetхsйg tiltott. Kйrd meg az adminisztrбtort, h engedйlyezze a beбllнtбsokban.',
		'confMsg_3' => 'Beбllнtбs szьksйges:',
		'confMsg_4' => 'A megfelelх mыkцdйshez be kell бllнtani a tar ъtvonalat a nem-windows szervereken, vagy a 7-zip ъtvonalat windows szervereken.',
		'confMsg_5' => 'Beбllнtбs elmentve!',
		'here' => 'itt',
		'restore' => 'File visszaбllнtбsa',
		'noFile' => 'Nincs backup file!',
		'e_files' => 'Kihagyott file-ok',
		'e_files2' => 'File-ok a Kihagyott listбban',
		'e_files3' => 'nem volt feldolgozva',
		'errorLog1' => 'Volt egy mыkцdйsi riport',
		'errorLog2' => 'Itt lбthatу',
		'errorLog3' => 'Mыkцdйsi riport',
		'errorLog4' => 'sql nem tцrцlhetх',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'title' => 'Cуpia de Seguranзa',
		'f1s1_title' => 'Fazer Cуpia de Seguranзa',
		'f1s1_title2' => 'Remover Cуpias de Seguranзa Antigos',
		'flsl_title3' => 'Recuperar Cуpia de Seguranзa',
		'flsl_title4' => 'Configuraзхes do Mуdulo',
		'flsl_title5' => 'Sobre a Cуpia de Seguranзa',
		'f1s1_label_all' => 'Todos',
		'f1s1_backupcreated' => 'Cуpia de seguranзa criada.',
		'clearWarning' => '<b><font color=red>Alerta:</font></b><br>Vocк estб prestes a apagar todos os arquivo *.gz contidos na pasta typo3temp/ (mesmo que nгo seja uma cуpia de seguranзa antiga!).',
		'function1' => 'Assegurar',
		'function2' => 'Restaurar',
		'function3' => 'Limpar',
		'function4' => 'Configuraзхes',
		'function5' => 'Sobre',
		'avBckps' => 'Cуpias de Seguranзa disponнveis:',
		'submit_backupnow' => 'Assegurar agora!',
		'wholetypo3conf' => 'Incluir o diretуrio typo3conf inteiro',
		'restoreFile' => 'Restaurar arquivo',
		'clearAll' => 'Remover todos os arquivos *.gz!',
		'clearFile' => 'Remover arquivo',
		'clearedOk' => 'foi removido!',
		'restoreOk' => 'foi restaurado!',
		'clearedAllOk' => 'Todos os arquivos *.gz foram removidos!',
		'executed' => 'Executado',
		'backupCreated' => 'Cуpia de Seguranзa Criada!',
		'downloadFile' => 'Baixar arquivo',
		'altDownloadMsg' => 'Se o arquivo nгo baixar automaticamente, vocк pode baixб-lo',
		'confMsg' => '(<em>Aviso: Talvez seja necessбrio limpar o cache apуs configurar a extensгo. Isso й necessбrio se a extensгo adicionar algum TypoScript dependente destas configuraзхes. </em>)<br /><br />',
		'confMsg_2' => 'Desculpe. Essa funcionalidade estб desabilitada. Por favor, consulte seu administrador de sistemas para modificar as configuraзхes da extensгo.',
		'confMsg_3' => 'Configuraзхes necessбrias:',
		'confMsg_4' => 'Para esta extensгo funcionar corretamente, vocк deve informar o caminho do tar para servidores nгo-windows, ou o caminho para o 7-Zip para servidores windows.',
		'confMsg_5' => 'Configuraзгo Salva!',
		'here' => 'baixar arquivo aqui',
		'restore' => 'Restaurar Arquivo',
		'noFile' => 'Nгo hб nenhum arquivo de Cуpia de Seguranзa!',
		'e_files' => 'Arquivos Excluнdos',
		'e_files2' => 'Arquivos na Lista de Exclusгo',
		'e_files3' => 'nгo foram processados',
		'errorLog1' => 'Hб um relatуrio de operaзгo',
		'errorLog2' => 'Ele pode ser visto aqui',
		'errorLog3' => 'Relatуrio de Operaзгo',
		'errorLog4' => 'sql nгo pode ser excluнdo',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>