#!/bin/sh

SCRIPT_DIR="$(cd "${0%/*}"; pwd)"

source "$SCRIPT_DIR/config"

mkdir -p "$DEPLOY_DIR"

if [ ! -d "$WP_CORE_DIR" ]; then
  "$SCRIPT_DIR/get-wp-core" || rm -rf "$WP_CORE_DIR" && exit 1
fi

# Old Website and Theme

cd "$SCRIPT_DIR"
  git submodule update --recursive
cd - &>/dev/null

# Site
rsync --archive --compress --delete "$LOCAL_DIR/" "$DEPLOY_DIR/"

# Uploads
rsync --archive --compress --delete "$LOCAL_DIR_UPLOADS/" "$DEPLOY_DIR/uploads/"

# Core
rsync --archive --compress "$WP_CORE_DIR/" "$DEPLOY_DIR/"
