#!/bin/sh

SSH_USER=editiontirol
SSH_HOST=eleven2

REMOTE_DIR='~/edition.tirol'
REMOTE_DIR_UPLOADS="$REMOTE_DIR/www/uploads"

LOCAL_DIR="$SCRIPT_DIR/www"
LOCAL_DIR_UPLOADS="$SCRIPT_DIR/../data/uploads"

WP_CORE_DIR="$SCRIPT_DIR/.cache/wordpress"
DEPLOY_DIR="$SCRIPT_DIR/.cache/deploy"
