#!/bin/sh

SCRIPT_DIR="$(cd "${0%/*}"; pwd)"

source "$SCRIPT_DIR/config"

if [ ! -d "$DEPLOY_DIR" ]; then
  "$SCRIPT_DIR/build" || rm -rf "$DEPLOY_DIR" && exit 1
fi

scp "$SCRIPT_DIR/wp-config-production.php" "$SSH_USER@$SSH_HOST:$REMOTE_DIR/" || exit 1

"$SCRIPT_DIR/sync-uploads"

rsync --archive --compress --delete-after "$DEPLOY_DIR/" "$SSH_USER@$SSH_HOST:$REMOTE_DIR/www/" \
  --exclude .DS_Store \
  --exclude .git

ssh editiontirol@eleven2 "if [ -d $REMOTE_DIR/www/uploads -a ! -L $REMOTE_DIR/www/uploads ]; then rm -rf $REMOTE_DIR/www/uploads; fi; ln -sfn $REMOTE_DIR_UPLOADS $REMOTE_DIR/www/uploads"
