#!/bin/sh

SCRIPT_DIR="$(cd "${0%/*}"; pwd)"

source "$SCRIPT_DIR/config"

if [ ! -d "$DEPLOY_DIR" ]; then
  "$SCRIPT_DIR/build" || rm -rf "$DEPLOY_DIR" && exit 1
fi

rsync --archive --compress --delete-after "$DEPLOY_DIR/" "$SSH_USER@$SSH_HOST:$REMOTE_DIR/www/" \
  --exclude .DS_Store \
  --exclude .git

scp "$SCRIPT_DIR/wp-config-production.php" "$SSH_USER@$SSH_HOST:$REMOTE_DIR/"
