#!/bin/sh

SCRIPT_DIR="$(cd "${0%/*}"; pwd)"

source "$SCRIPT_DIR/config"

CACHE=/tmp

WP_VERSION='4.4.1'
WP_LANGUAGES=(de_DE de_DE_formal)

WP_VERSION_MAJOR_MINOR=${WP_VERSION%%.*}.$(minor=${WP_VERSION#*.} && echo ${minor%%.*})

download_and_check() {

  url="${1}"
  name="${url##*/}"
  path="$CACHE/$name"
  sha256=${2}

  if [ ! -f "$path" ]; then
    echo "Downloading ${name}"
    curl --progress-bar --location "$url" -o "$path"
  else
    echo "Already downloaded: $path"
  fi

  echo "Extracting $name"
  unzip -q -o "$path" -d "$CACHE"

}

rm -rf "$CACHE/wordpress"


# WordPress Core

for WP_LANGUAGE in ${WP_LANGUAGES[*]}; do
  download_and_check "https://de.wordpress.org/wordpress-$WP_VERSION-$WP_LANGUAGE.zip"
done


# Plugins

hash msgfmt || brew install gettext && brew link gettext --force

for plugin in \
  language-fallback@1.0.3 \
  mailgun@1.4.1 \
  redirection@2.4.3 \
  regenerate-thumbnails@2.2.6 \
  underconstruction@1.16 \
  woocommerce@2.4.13 \
  wp-optimize@1.8.9.10
do
  version=${plugin##*@}
  plugin=${plugin%@*}

  download_and_check "https://downloads.wordpress.org/plugin/$plugin.$version.zip"

  for WP_LANGUAGE in ${WP_LANGUAGES[*]}; do
    file="$CACHE/wordpress/wp-content/languages/plugins/$plugin-$WP_LANGUAGE"
    url="https://i18n.trac.wordpress.org/export/latest/plugins/$plugin/$version/$WP_LANGUAGE/${file##*/}.po"


    if curl --silent "$url" --head --fail --output /dev/null; then
      echo "Downloading '$WP_LANGUAGE' translation for $plugin"

      curl --progress-bar --location "$url" -o "$file.po"

      msgfmt "$file.po" -o "$file.mo"
    fi
  done

  rsync --archive "$CACHE/$plugin/" "$CACHE/wordpress/wp-content/plugins/$plugin" \
    --exclude '/license.txt' \
    --exclude '/readme.txt'
done

brew unlink gettext


rsync --delete-excluded --archive "$CACHE/wordpress/" "$WP_CORE_DIR" \
  --exclude 'license.txt' \
  --exclude 'liesmich.html' \
  --exclude 'readme.html' \
  --exclude 'wp-config-sample.php' \
  --exclude 'wp-content/plugins/hello.php' \
  --exclude 'wp-content/plugins/akismet' \
  --exclude 'wp-content/languages/plugins/akismet*' \
  --exclude 'wp-content/themes/twenty*' \
  --exclude 'wp-content/languages/themes/twenty*' \
  --exclude 'wp-content/plugins/wp-optimize/index.htm'
