#!/bin/sh

SCRIPT_DIR="$(cd "${0%/*}"; pwd)"

source "$SCRIPT_DIR/config" || exit 1

CACHE=/tmp

WP_VERSION='4.7'
WP_LANGUAGES=(de_DE de_DE_formal)

WP_VERSION_MAJOR_MINOR=${WP_VERSION%%.*}.$(minor=${WP_VERSION#*.} && echo ${minor%%.*})

download_and_check() {
  url="${1}"
  name="${url##*/}"
  path="$CACHE/$name"

  if [ ! -f "$path" ]; then
    echo "Downloading ${name}"
    curl --progress-bar --location "$url" -o "$path" || exit 1
  else
    echo "Already downloaded: $path"
  fi

  echo "Extracting $name"
  unzip -q -o "$path" -d "$CACHE" || exit 1

}

rm -rf "$CACHE/wordpress" || exit 1


# WordPress Core

for WP_LANGUAGE in ${WP_LANGUAGES[*]}; do
  download_and_check "https://de.wordpress.org/wordpress-$WP_VERSION-$WP_LANGUAGE.zip"
done


# Plugins

hash msgfmt || brew install gettext && brew link gettext --force || exit 1

for plugin in \
  language-fallback@1.0.3 \
  mailgun@1.5.5 \
  redirection@2.5 \
  regenerate-thumbnails@2.2.6 \
  underconstruction@1.17 \
  woocommerce@2.6.11 \
  wp-optimize@2.1.0
do
  plugin_version="${plugin##*@}"
  plugin_version_major_minor="${plugin_version%%.*}.$(minor="${plugin_version#*.}" && echo "${minor%%.*}")"

  plugin="${plugin%@*}"

  download_and_check "https://downloads.wordpress.org/plugin/$plugin.$plugin_version.zip"

  for WP_LANGUAGE in ${WP_LANGUAGES[*]}; do
    for version in "${plugin_version_major_minor}" "${plugin_version}"; do
      file="$CACHE/wordpress/wp-content/languages/plugins/$plugin-$WP_LANGUAGE"
      url="https://i18n.trac.wordpress.org/export/latest/plugins/$plugin/$version/$WP_LANGUAGE/${file##*/}.po"

      if curl --silent "$url" --head --fail --output /dev/null; then
        echo "Downloading '$WP_LANGUAGE' translation for $plugin"

        curl --progress-bar --location "$url" -o "$file.po" || exit 1

        msgfmt "$file.po" -o "$file.mo" || exit 1
      fi
    done

    language="${WP_LANGUAGE%%_*}"
    lang_version='default'

    if [[ $WP_LANGUAGE == *"formal" ]]; then
      lang_version='formal'
    fi

    url="https://translate.wordpress.org/projects/wp-plugins/$plugin/dev/$language/$lang_version/export-translations?filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&format=mo"

    file="$CACHE/wordpress/wp-content/languages/plugins/$plugin-$WP_LANGUAGE"
    if curl --silent "$url" --head --fail --output /dev/null; then
      echo "Downloading '$WP_LANGUAGE' translation for $plugin"

      curl --progress-bar --location "$url" -o "$file.mo" || exit 1
    fi
  done

  rsync --archive "$CACHE/$plugin/" "$CACHE/wordpress/wp-content/plugins/$plugin" \
    --exclude '/license.txt' \
    --exclude '/readme.txt' || exit 1
done

brew unlink gettext


rsync --delete-excluded --archive "$CACHE/wordpress/" "$WP_CORE_DIR" \
  --exclude 'license.txt' \
  --exclude 'liesmich.html' \
  --exclude 'readme.html' \
  --exclude 'wp-config-sample.php' \
  --exclude 'wp-content/plugins/hello.php' \
  --exclude 'wp-content/plugins/akismet' \
  --exclude 'wp-content/languages/plugins/akismet*' \
  --exclude 'wp-content/themes/twenty*' \
  --exclude 'wp-content/languages/themes/twenty*' \
  --exclude 'wp-content/plugins/wp-optimize/index.htm' \
  --exclude 'wp-content/plugins/redirection/locale/redirection-de_DE.*' || exit 1
