#!/bin/sh

SCRIPT_DIR="$(cd "${0%/*}"; pwd)"

source "$SCRIPT_DIR/config"

rsync --archive --compress --progress "$SSH_USER@$SSH_HOST:$REMOTE_DIR_UPLOADS/" "$LOCAL_DIR_UPLOADS/" \
    && "$SCRIPT_DIR/prune-uploads"
