#!/bin/sh

SCRIPT_DIR="$(cd "$(dirname "${0}")"; pwd)"

rsync --archive --compress --progress --delete-after --exclude .DS_Store --exclude .git --exclude .sass-cache "${SCRIPT_DIR}/www/" "editiontirol@eleven2:~/public_html/"
